---
name: CI

# Ensure only one job per branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  check:
    name: "${{ matrix.template.name }}"

    strategy:
      matrix:
        template:
          - name: asciidoc
            pre_run: null
            run: null

          - name: default
            pre_run: null
            run: null

          - name: go-bin
            pre_run: null
            run: |
              nix develop --command just bin
              ./bin/exe version
              ./bin/exe help

          - name: python-pkg
            pre_run: |
              nix develop --command uv lock
              git add uv.lock
            run: |
              nix develop --command ruff check --select E,F,UP,B,SIM,I
              nix develop --command black -t py313 --check .

          - name: python-script
            pre_run: null
            run: |
              nix develop --command ruff check --select E,F,UP,B,SIM,I
              nix develop --command black -t py312 --check .
              ./script.py --version
              ./script.py --help

          - name: ruby-script
            pre_run: null
            run: |
              ./script.rb --version
              ./script.rb --help

          - name: sh-script
            pre_run: null
            run: |
              ./script.sh --version
              ./script.sh --help

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Pre-run
        if: "${{ matrix.template.pre_run != null }}"
        run: |
          cd "${{ matrix.template.name }}"
          while IFS= read -r cmd; do
            ${cmd}
          done < <(echo -e "${{ matrix.template.pre_run }}")

      - name: Check nix formatting
        run: |
          cd "${{ matrix.template.name }}"
          nix develop --command alejandra --check $(git ls-files '*.nix')

      - name: Check flake
        run: |
          cd "${{ matrix.template.name }}"
          nix flake check --all-systems --no-build

      - name: Check template
        if: "${{ matrix.template.run != null }}"
        run: |
          cd "${{ matrix.template.name }}"
          while IFS= read -r cmd; do
            ${cmd}
          done < <(echo -e "${{ matrix.template.run }}")
